# Generated by Django 6.0.1 on 2026-02-01 06:03

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.authentication.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_email_ece7f7_idx",
            old_name="authenticat_email_d74434_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_role_f90fd2_idx",
            old_name="authenticat_role_7fb088_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_created_bd0e77_idx",
            old_name="authenticat_created_51c146_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=True, help_text="Account approved by admin"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="auth_user",
        ),
    ]
