# Generated by Django 6.0.1 on 2026-02-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("user", "User"),
                    ("seller", "Seller"),
                ],
                default="user",
                help_text="User role in the system",
                max_length=10,
            ),
        ),
    ]
