# Generated by Django 6.0.1 on 2026-03-15 06:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("performance", "0002_alter_order_return_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("version", models.CharField(max_length=20)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("performance_predictor", "Performance Predictor"),
                            ("trend_analyzer", "Trend Analyzer"),
                            ("anomaly_detector", "Anomaly Detector"),
                            ("recommendation_engine", "Recommendation Engine"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="training",
                        max_length=15,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Model configuration parameters"
                    ),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "recall",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("total_predictions", models.PositiveIntegerField(default=0)),
                ("last_trained_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Models",
                "ordering": ["-created_at"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("trend_analysis", "Trend Analysis"),
                            ("performance_alert", "Performance Alert"),
                            ("recommendation", "Recommendation"),
                            ("prediction", "Prediction"),
                            ("ranking_change", "Ranking Change"),
                            ("benchmark_comparison", "Benchmark Comparison"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("recommendation", models.TextField(blank=True)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="AI confidence level (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "analysis_data",
                    models.JSONField(
                        default=dict, help_text="Raw analysis data and metrics"
                    ),
                ),
                (
                    "predicted_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Predicted metric value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "prediction_timeframe_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Prediction timeframe in days", null=True
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this insight becomes irrelevant",
                        null=True,
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="performance.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Insight",
                "verbose_name_plural": "Performance Insights",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "-created_at"],
                        name="ai_insights_seller__3c9e10_idx",
                    ),
                    models.Index(
                        fields=["insight_type", "-created_at"],
                        name="ai_insights_insight_db448f_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="ai_insights_severit_c395cf_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="ai_insights_status_ae5648_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PredictiveAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("performance_decline", "Performance Decline"),
                            ("return_rate_spike", "Return Rate Spike"),
                            ("delivery_delay_risk", "Delivery Delay Risk"),
                            ("rating_drop_risk", "Rating Drop Risk"),
                            ("sales_decline", "Sales Decline"),
                            ("threshold_breach", "Threshold Breach"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("suggested_actions", models.TextField(blank=True)),
                ("predicted_metric", models.CharField(max_length=100)),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "predicted_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "prediction_date",
                    models.DateTimeField(
                        help_text="When the predicted event is expected to occur"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictive_alerts",
                        to="performance.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predictive Alert",
                "verbose_name_plural": "Predictive Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "-created_at"],
                        name="ai_insights_seller__819e52_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "-created_at"],
                        name="ai_insights_alert_t_5b1e69_idx",
                    ),
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="ai_insights_priorit_3b0b17_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="ai_insights_is_acti_3f99f6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RankingChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_rank", models.PositiveIntegerField()),
                ("new_rank", models.PositiveIntegerField()),
                ("rank_change", models.IntegerField()),
                ("previous_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("new_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("score_change", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "change_factors",
                    models.JSONField(
                        default=dict,
                        help_text="AI-identified factors contributing to ranking change",
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of ranking change"
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_changes",
                        to="performance.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ranking Change",
                "verbose_name_plural": "Ranking Changes",
                "ordering": ["-change_date"],
                "indexes": [
                    models.Index(
                        fields=["seller", "-change_date"],
                        name="ai_insights_seller__5917d5_idx",
                    )
                ],
            },
        ),
    ]
