# Generated by Django 6.0.1 on 2026-03-15 06:44

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("register", "Registration"),
                            ("password_change", "Password Change"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("report_generate", "Report Generate"),
                            ("report_download", "Report Download"),
                            ("export_data", "Data Export"),
                            ("import_data", "Data Import"),
                            ("performance_calculate", "Performance Calculation"),
                            ("seller_evaluate", "Seller Evaluation"),
                            ("status_change", "Status Change"),
                            ("failed_login", "Failed Login"),
                            ("permission_denied", "Permission Denied"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("description", models.TextField()),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional event details in JSON format",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DataChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("field_type", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "audit_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_changes",
                        to="audit_trail.auditevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Change Log",
                "verbose_name_plural": "Data Change Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(db_index=True, default=False)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["email", "-timestamp"],
                        name="audit_trail_email_182585_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="audit_trail_ip_addr_6156c3_idx",
                    ),
                    models.Index(
                        fields=["success", "-timestamp"],
                        name="audit_trail_success_cb2fbb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(db_index=True, max_length=100)),
                ("metric_value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tags",
                    models.JSONField(
                        default=dict, help_text="Additional metric tags in JSON format"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "System Metric",
                "verbose_name_plural": "System Metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "-timestamp"],
                        name="audit_trail_metric__1fe3b6_idx",
                    )
                ],
                "unique_together": {("metric_name", "timestamp")},
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="audit_trail_event_t_6e391c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["user", "-timestamp"], name="audit_trail_user_id_056a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["severity", "-timestamp"], name="audit_trail_severit_0ccdc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["success", "-timestamp"], name="audit_trail_success_b03ef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["ip_address", "-timestamp"],
                name="audit_trail_ip_addr_9d40d9_idx",
            ),
        ),
    ]
