# Generated by Django 6.0.1 on 2026-02-01 02:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="Registered business name", max_length=255
                    ),
                ),
                (
                    "business_registration",
                    models.CharField(
                        help_text="Business registration number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Seller business description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("under_review", "Under Review"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current seller performance status",
                        max_length=20,
                    ),
                ),
                (
                    "performance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Computed performance score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, help_text="Total completed orders"
                    ),
                ),
                (
                    "total_sales_volume",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total sales amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "average_delivery_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average delivery time in days",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average customer rating (0-5)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                    ),
                ),
                (
                    "return_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of returned orders",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status_updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last status change timestamp",
                    ),
                ),
                (
                    "last_evaluated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last performance evaluation timestamp",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller",
                "verbose_name_plural": "Sellers",
                "ordering": ["-performance_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique order identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer email address", max_length=254
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current order status",
                        max_length=20,
                    ),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total order value",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Order placement timestamp",
                    ),
                ),
                (
                    "shipped_date",
                    models.DateTimeField(
                        blank=True, help_text="Order shipment timestamp", null=True
                    ),
                ),
                (
                    "delivered_date",
                    models.DateTimeField(
                        blank=True, help_text="Order delivery timestamp", null=True
                    ),
                ),
                (
                    "delivery_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calculated delivery time in days",
                        null=True,
                    ),
                ),
                (
                    "is_returned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether order was returned",
                    ),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True, help_text="Return request timestamp", null=True
                    ),
                ),
                (
                    "return_reason",
                    models.TextField(blank=True, help_text="Reason for return"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Seller who fulfilled this order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="performance.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        help_text="Customer who provided feedback", max_length=254
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Customer rating (1-5 stars)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Customer feedback comment"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Associated order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="performance.order",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Seller being rated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="performance.seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Feedback",
                "verbose_name_plural": "Customer Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="seller",
            index=models.Index(fields=["status"], name="performance_status_a5e563_idx"),
        ),
        migrations.AddIndex(
            model_name="seller",
            index=models.Index(
                fields=["-performance_score"], name="performance_perform_6b3c2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seller",
            index=models.Index(
                fields=["-created_at"], name="performance_created_d25f00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seller",
            index=models.Index(
                fields=["status", "-performance_score"],
                name="performance_status_1f779c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["seller", "-order_date"], name="performance_seller__6890bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["seller", "status"], name="performance_seller__e13293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-order_date"], name="performance_status_c9980a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["seller", "is_returned"], name="performance_seller__e480f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-order_date"], name="performance_order_d_c1e539_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("order_amount__gt", 0)),
                name="order_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="customerfeedback",
            index=models.Index(
                fields=["seller", "-created_at"], name="performance_seller__42d488_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerfeedback",
            index=models.Index(
                fields=["seller", "rating"], name="performance_seller__69b173_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerfeedback",
            index=models.Index(
                fields=["-created_at"], name="performance_created_09ec38_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerfeedback",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="rating_valid_range",
            ),
        ),
    ]
