# Generated by Django 6.0.1 on 2026-03-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="return_reason",
            field=models.TextField(
                blank=True, help_text="Reason for return", null=True
            ),
        ),
    ]
