# Generated by Django 6.0.1 on 2026-04-02 08:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_alter_order_return_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceConfig",
            fields=[
                ("instance_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "weight_sales",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Weight for sales score (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "weight_delivery",
                    models.PositiveSmallIntegerField(
                        default=25,
                        help_text="Weight for delivery score (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "weight_rating",
                    models.PositiveSmallIntegerField(
                        default=35,
                        help_text="Weight for rating score (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "weight_returns",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Weight for returns penalty (0-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "sales_threshold_excellent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100000.00"),
                        help_text="Sales amount for excellent score",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "sales_threshold_good",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50000.00"),
                        help_text="Sales amount for good score",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "sales_threshold_low",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000.00"),
                        help_text="Sales amount threshold for low score warning",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "delivery_threshold_excellent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Days for excellent delivery score",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "delivery_threshold_good",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Days for good delivery score",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "delivery_threshold_mid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Days for mid delivery score",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "delivery_threshold_slow",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("14.00"),
                        help_text="Days threshold - above this is slow delivery",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "return_rate_threshold_excellent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Return rate % for excellent score",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "return_rate_threshold_good",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Return rate % for good score",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "return_rate_threshold_mid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Return rate % for mid score",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "return_rate_threshold_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Return rate % threshold - above this is penalised heavily",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "status_threshold_active",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="Score threshold for ACTIVE status (≥ this score)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status_threshold_under_review",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="Score threshold for UNDER_REVIEW status (≥ this score)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Performance Configuration",
                "verbose_name_plural": "Performance Configuration",
            },
        ),
    ]
