"""
Export Service for Seller Performance Reports.
Implements FR-12: External Report Export and FR-03: Generate Seller Performance Report.

Supports:
- PDF report generation
- CSV data export
- Excel export
- Custom report templates
- Batch export operations
"""
import csv
import json
import logging
from datetime import datetime, timedelta
from decimal import Decimal
from typing import Dict, List, Optional, Any
from io import BytesIO, StringIO
import pandas as pd

# PDF Generation
try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.platypus import PageBreak, Image
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False

from django.http import HttpResponse
from django.template.loader import render_to_string
from django.conf import settings
from django.utils import timezone
from django.db.models import Avg, Count, Sum, Q

from apps.performance.models import Seller, Order, CustomerFeedback
from apps.ai_insights.models import PerformanceInsight, PredictiveAlert
from apps.audit_trail.models import AuditEvent

logger = logging.getLogger(__name__)


class ExportService:
    """
    Comprehensive export service for seller performance data.
    """
    
    def __init__(self):
        self.export_dir = getattr(settings, 'EXPORT_ROOT', settings.BASE_DIR / 'exports')
    
    def generate_seller_report_pdf(self, seller: Seller, user, 
                                  include_ai_insights: bool = True) -> BytesIO:
        """
        Generate comprehensive PDF report for a seller.
        Implements FR-03: Generate Seller Performance Report.
        """
        if not PDF_AVAILABLE:
            raise ImportError("PDF generation requires reportlab package")
        
        try:
            # Create PDF buffer
            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=A4)
            story = []
            
            # Get styles
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=18,
                alignment=TA_CENTER,
                spaceAfter=30
            )
            
            # Title
            title = f"Performance Report - {seller.business_name}"
            story.append(Paragraph(title, title_style))
            story.append(Spacer(1, 20))
            
            # Report metadata
            metadata_data = [
                ['Report Generated:', timezone.now().strftime('%Y-%m-%d %H:%M:%S')],
                ['Generated By:', user.email],
                ['Seller Business Name:', seller.business_name],
                ['Business Registration:', seller.business_registration],
                ['Current Status:', seller.get_status_display()],
                ['Performance Score:', f"{seller.performance_score}/100"]
            ]
            
            metadata_table = Table(metadata_data, colWidths=[2*inch, 4*inch])
            metadata_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(metadata_table)
            story.append(Spacer(1, 20))
            
            # Performance Metrics Section
            story.append(Paragraph("Performance Metrics", styles['Heading2']))
            
            # Get performance data
            performance_data = self._get_seller_performance_data(seller)
            
            metrics_data = [
                ['Metric', 'Value', 'Benchmark'],
                ['Total Orders', str(performance_data['total_orders']), 'N/A'],
                ['Total Sales Volume', f"${performance_data['total_sales']:,.2f}", 'N/A'],
                ['Average Rating', f"{performance_data['avg_rating']:.2f}/5.0", '≥4.0'],
                ['Average Delivery Days', f"{performance_data['avg_delivery_days']:.1f}", '≤5.0'],
                ['Return Rate', f"{performance_data['return_rate']:.1f}%", '≤5.0%'],
                ['Order Completion Rate', f"{performance_data['completion_rate']:.1f}%", '≥95.0%']
            ]
            
            metrics_table = Table(metrics_data, colWidths=[2.5*inch, 1.5*inch, 1.5*inch])
            metrics_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(metrics_table)
            story.append(Spacer(1, 20))
            
            # Recent Orders Section
            story.append(Paragraph("Recent Orders (Last 30 Days)", styles['Heading2']))
            
            recent_orders = Order.objects.filter(
                seller=seller,
                order_date__gte=timezone.now() - timedelta(days=30)
            ).order_by('-order_date')[:10]
            
            if recent_orders:
                orders_data = [['Order Number', 'Date', 'Amount', 'Status', 'Delivery Days']]
                for order in recent_orders:
                    orders_data.append([
                        order.order_number,
                        order.order_date.strftime('%Y-%m-%d'),
                        f"${order.order_amount:.2f}",
                        order.get_status_display(),
                        str(order.delivery_days) if order.delivery_days else 'N/A'
                    ])
                
                orders_table = Table(orders_data, colWidths=[1.2*inch, 1*inch, 1*inch, 1.2*inch, 1*inch])
                orders_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black)
                ]))
                
                story.append(orders_table)
            else:
                story.append(Paragraph("No orders in the last 30 days.", styles['Normal']))
            
            story.append(Spacer(1, 20))
            
            # AI Insights Section (if enabled)
            if include_ai_insights:
                story.append(Paragraph("AI-Powered Insights", styles['Heading2']))
                
                insights = PerformanceInsight.objects.filter(
                    seller=seller,
                    status=PerformanceInsight.Status.ACTIVE
                ).order_by('-created_at')[:5]
                
                if insights:
                    for insight in insights:
                        insight_text = f"<b>{insight.title}</b><br/>{insight.description}"
                        if insight.recommendation:
                            insight_text += f"<br/><i>Recommendation: {insight.recommendation[:200]}...</i>"
                        
                        story.append(Paragraph(insight_text, styles['Normal']))
                        story.append(Spacer(1, 10))
                else:
                    story.append(Paragraph("No AI insights available.", styles['Normal']))
                
                story.append(Spacer(1, 20))
            
            # Build PDF
            doc.build(story)
            buffer.seek(0)
            
            # Log report generation
            AuditEvent.log_event(
                event_type=AuditEvent.EventType.REPORT_GENERATE,
                user=user,
                description=f"PDF report generated for seller: {seller.business_name}",
                severity=AuditEvent.Severity.MEDIUM,
                seller_id=seller.id,
                report_type='pdf'
            )
            
            return buffer
            
        except Exception as e:
            logger.error(f"PDF generation failed for seller {seller.id}: {e}")
            raise
    
    def export_sellers_csv(self, user, filters: Optional[Dict] = None) -> HttpResponse:
        """
        Export sellers data to CSV format.
        """
        try:
            # Build queryset with filters
            queryset = Seller.objects.all()
            
            if filters:
                if filters.get('status'):
                    queryset = queryset.filter(status=filters['status'])
                if filters.get('min_score'):
                    queryset = queryset.filter(performance_score__gte=filters['min_score'])
                if filters.get('max_score'):
                    queryset = queryset.filter(performance_score__lte=filters['max_score'])
            
            # Create CSV response
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = f'attachment; filename="sellers_export_{timezone.now().strftime("%Y%m%d_%H%M%S")}.csv"'
            
            writer = csv.writer(response)
            
            # Write headers
            headers = [
                'ID', 'Business Name', 'Business Registration', 'Email',
                'Status', 'Performance Score', 'Total Orders', 'Total Sales',
                'Average Rating', 'Return Rate', 'Created Date'
            ]
            writer.writerow(headers)
            
            # Write data rows
            for seller in queryset:
                writer.writerow([
                    seller.id,
                    seller.business_name,
                    seller.business_registration,
                    seller.user.email,
                    seller.status,
                    f"{seller.performance_score:.2f}",
                    seller.total_orders,
                    f"{seller.total_sales_volume:.2f}",
                    f"{seller.average_rating:.2f}",
                    f"{seller.return_rate:.2f}",
                    seller.created_at.strftime('%Y-%m-%d %H:%M:%S')
                ])
            
            # Log export
            AuditEvent.log_event(
                event_type=AuditEvent.EventType.EXPORT_DATA,
                user=user,
                description=f"Sellers data exported to CSV ({queryset.count()} records)",
                severity=AuditEvent.Severity.MEDIUM,
                export_type='csv',
                record_count=queryset.count()
            )
            
            return response
            
        except Exception as e:
            logger.error(f"CSV export failed: {e}")
            raise
    
    def export_orders_csv(self, user, seller_id: Optional[int] = None,
                         date_from: Optional[datetime] = None,
                         date_to: Optional[datetime] = None) -> HttpResponse:
        """
        Export orders data to CSV format.
        """
        try:
            # Build queryset
            queryset = Order.objects.all()
            
            if seller_id:
                queryset = queryset.filter(seller_id=seller_id)
            if date_from:
                queryset = queryset.filter(order_date__gte=date_from)
            if date_to:
                queryset = queryset.filter(order_date__lte=date_to)
            
            # Create CSV response
            response = HttpResponse(content_type='text/csv')
            filename = f"orders_export_{timezone.now().strftime('%Y%m%d_%H%M%S')}.csv"
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            
            writer = csv.writer(response)
            
            # Write headers
            headers = [
                'Order Number', 'Seller Business Name', 'Customer Email',
                'Order Amount', 'Order Date', 'Status', 'Shipped Date',
                'Delivered Date', 'Delivery Days', 'Is Returned', 'Return Reason'
            ]
            writer.writerow(headers)
            
            # Write data rows
            for order in queryset.select_related('seller'):
                writer.writerow([
                    order.order_number,
                    order.seller.business_name,
                    order.customer_email,
                    f"{order.order_amount:.2f}",
                    order.order_date.strftime('%Y-%m-%d %H:%M:%S'),
                    order.status,
                    order.shipped_date.strftime('%Y-%m-%d %H:%M:%S') if order.shipped_date else '',
                    order.delivered_date.strftime('%Y-%m-%d %H:%M:%S') if order.delivered_date else '',
                    order.delivery_days or '',
                    'Yes' if order.is_returned else 'No',
                    order.return_reason or ''
                ])
            
            # Log export
            AuditEvent.log_event(
                event_type=AuditEvent.EventType.EXPORT_DATA,
                user=user,
                description=f"Orders data exported to CSV ({queryset.count()} records)",
                severity=AuditEvent.Severity.MEDIUM,
                export_type='csv',
                record_count=queryset.count(),
                seller_id=seller_id
            )
            
            return response
            
        except Exception as e:
            logger.error(f"Orders CSV export failed: {e}")
            raise
    
    def export_performance_report_excel(self, user, include_insights: bool = True) -> HttpResponse:
        """
        Export comprehensive performance report to Excel format.
        """
        try:
            # Create Excel buffer
            buffer = BytesIO()
            
            with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                
                # Sellers summary sheet
                sellers_data = []
                for seller in Seller.objects.all():
                    perf_data = self._get_seller_performance_data(seller)
                    sellers_data.append({
                        'Business Name': seller.business_name,
                        'Registration': seller.business_registration,
                        'Email': seller.user.email,
                        'Status': seller.get_status_display(),
                        'Performance Score': float(seller.performance_score),
                        'Total Orders': perf_data['total_orders'],
                        'Total Sales': float(perf_data['total_sales']),
                        'Average Rating': perf_data['avg_rating'],
                        'Average Delivery Days': perf_data['avg_delivery_days'],
                        'Return Rate %': perf_data['return_rate'],
                        'Completion Rate %': perf_data['completion_rate']
                    })
                
                sellers_df = pd.DataFrame(sellers_data)
                sellers_df.to_excel(writer, sheet_name='Sellers Summary', index=False)
                
                # Recent orders sheet
                recent_orders = Order.objects.filter(
                    order_date__gte=timezone.now() - timedelta(days=30)
                ).select_related('seller')
                
                orders_data = []
                for order in recent_orders:
                    orders_data.append({
                        'Order Number': order.order_number,
                        'Seller': order.seller.business_name,
                        'Customer Email': order.customer_email,
                        'Amount': float(order.order_amount),
                        'Date': order.order_date,
                        'Status': order.get_status_display(),
                        'Delivery Days': order.delivery_days,
                        'Returned': 'Yes' if order.is_returned else 'No'
                    })
                
                orders_df = pd.DataFrame(orders_data)
                orders_df.to_excel(writer, sheet_name='Recent Orders', index=False)
                
                # AI Insights sheet (if enabled)
                if include_insights:
                    insights_data = []
                    for insight in PerformanceInsight.objects.filter(
                        status=PerformanceInsight.Status.ACTIVE
                    ).select_related('seller'):
                        insights_data.append({
                            'Seller': insight.seller.business_name,
                            'Type': insight.get_insight_type_display(),
                            'Severity': insight.get_severity_display(),
                            'Title': insight.title,
                            'Description': insight.description,
                            'Confidence': float(insight.confidence_score),
                            'Created': insight.created_at
                        })
                    
                    insights_df = pd.DataFrame(insights_data)
                    insights_df.to_excel(writer, sheet_name='AI Insights', index=False)
            
            buffer.seek(0)
            
            # Create response
            response = HttpResponse(
                buffer.getvalue(),
                content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            )
            filename = f"performance_report_{timezone.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            
            # Log export
            AuditEvent.log_event(
                event_type=AuditEvent.EventType.EXPORT_DATA,
                user=user,
                description="Performance report exported to Excel",
                severity=AuditEvent.Severity.MEDIUM,
                export_type='excel'
            )
            
            return response
            
        except Exception as e:
            logger.error(f"Excel export failed: {e}")
            raise
    
    def _get_seller_performance_data(self, seller: Seller) -> Dict[str, Any]:
        """Get comprehensive performance data for a seller."""
        # Get order statistics
        orders = Order.objects.filter(seller=seller)
        total_orders = orders.count()
        
        if total_orders == 0:
            return {
                'total_orders': 0,
                'total_sales': Decimal('0.00'),
                'avg_rating': 0.0,
                'avg_delivery_days': 0.0,
                'return_rate': 0.0,
                'completion_rate': 0.0
            }
        
        # Calculate metrics
        total_sales = orders.aggregate(Sum('order_amount'))['order_amount__sum'] or Decimal('0.00')
        
        delivered_orders = orders.filter(status=Order.Status.DELIVERED)
        completion_rate = (delivered_orders.count() / total_orders) * 100 if total_orders > 0 else 0
        
        returned_orders = orders.filter(is_returned=True).count()
        return_rate = (returned_orders / total_orders) * 100 if total_orders > 0 else 0
        
        # Average delivery days
        delivery_days = delivered_orders.exclude(delivery_days__isnull=True).aggregate(
            Avg('delivery_days'))['delivery_days__avg'] or 0
        
        # Average rating from feedback
        avg_rating = CustomerFeedback.objects.filter(
            order__seller=seller
        ).aggregate(Avg('rating'))['rating__avg'] or 0
        
        return {
            'total_orders': total_orders,
            'total_sales': total_sales,
            'avg_rating': float(avg_rating),
            'avg_delivery_days': float(delivery_days),
            'return_rate': float(return_rate),
            'completion_rate': float(completion_rate)
        }
    
    def get_available_export_formats(self) -> List[Dict[str, str]]:
        """Get list of available export formats."""
        formats = [
            {'format': 'csv', 'name': 'CSV', 'description': 'Comma-separated values'},
            {'format': 'excel', 'name': 'Excel', 'description': 'Microsoft Excel format'},
        ]
        
        if PDF_AVAILABLE:
            formats.append({
                'format': 'pdf', 
                'name': 'PDF', 
                'description': 'Portable Document Format'
            })
        
        return formats